### ISSUE TITLE
What do the different status messages mean?

### ISSUE THREAD

**Issue by 1HighDuke** [rfetick/MPU6050_light#11]
Hello all,

Does anyone know what the different error statuses mean when initializing the device? I keep getting  MPU6050 status: 4 and MPU status: 2 errors when powering the device. I'd like to know what these mean?

Thanks!

**Comment by rfetick** [comment]
Hello,

The returned status is the one from the Arduino *Wire* library. Please have a look at the documentation there
[https://www.arduino.cc/en/Reference/WireEndTransmission](https://www.arduino.cc/en/Reference/WireEndTransmission)

Kind regards,

Romain
