### ISSUE TITLE
mpu6050 status

### ISSUE THREAD

**Issue by zfranco55** [rfetick/MPU6050_light#16]
I changed the value of the following line in MPU6050_light.h
`#define MPU6050_ADDR                  0x68`
 from:
0x68 to 0x69.
the example sketch shows me on the serial monitor the writing:
MPU6050 status: 4
what is it due to?
the code i am using with cpu stm32 (mini maple) in the arduino ide.

**Comment by rfetick** [comment]
The MPU6050 library status code is forwarded from the [Arduino Wire library](https://www.arduino.cc/en/Reference/WireEndTransmission). Please have a look at it.

Kind regards,

Romain
