### ISSUE TITLE
Fustion with magnetometer

### ISSUE THREAD

**Issue by batata004** [rfetick/MPU6050_light#27]
Hi my friend, have you ever tried fusing this library of yours with data from magnetometer to prevent drift on the gyro? If so, could you point me in the right direction?

BTW, your library is really great! Works perfectly and apart from the drift on yaw, its produces an awesome result!

**Comment by rfetick** [comment]
Hello batata004,

No I have never tried this, but obviously merging MPU6050 data with other sensors (GPS, magnetometer) would help in estimating the system state. I would recommand you to use Kalman filter to do so. I have written a Kalman filter library, but you can also find other libraries.

Cheers,

Romain
