### ISSUE TITLE
M5Stack Core Esp32

### ISSUE THREAD

**Issue by cacb-wg** [rfetick/MPU6050_light#5]
Great work !!!

I would like to use this library with the M5Stack Core Esp32. It is possible ? Can you give any guidance or script? 
Thank you.
Regards.

**Comment by rfetick** [comment]
Hello Cacb-wg,

It seems there is an issue with ESP type controllers. You may have a look at [this issue](https://github.com/rfetick/MPU6050_light/issues/1). In this issue discussion, there are some hints on the problem, but no implemented safe solution for now.
