### ISSUE TITLE
Where can i find and change the pin connection

### ISSUE THREAD

**Issue by LedHat** [rfetick/MPU6050_light#8]
Hey,thanks for the library but where can i find to wich pins you connected the mpu and where can i possibly change it?

**Comment by rfetick** [comment]
The MPU6050 should be connected to the default SDA and SCL pins of the micro-controller. Maybe you can have a look at the Arduino [Wire library](https://www.arduino.cc/en/Reference/Wire) to know the corresponding pin numbers.

Kind regards,

Romain

**Comment by LedHat** [comment]
I see, how stupid the question sounds afterward. I was just confused because of the other I2c pins for an magnetometer. Is it planned to make magnetometer possible in this library too?

**Comment by rfetick** [comment]
Unfortunately I don't plan to include magnetometer. The main reason is that I don't have access to a magnetometer, so it will be impossible to debug for me. The second reason is that I try to keep the library efficient but as simple as possible, it is often a compromise between simplicity and interesting new features.

Kind regards,

Romain

**Comment by LedHat** [comment]
Alright, no problem

Am Mi., 27. Jan. 2021 um 23:40 Uhr schrieb Romain JL. FETICK <
notifications@github.com>:
